version: "3.8"

services:
  usuarios:
    build: .
    container_name: etl_usuarios
    environment:
      # 👇 IP real (o hostname) de tu VM 2
      MS1_URL: "http://98.88.24.29:8000"
    volumes:
      - ./output:/app/output   # para inspeccionar CSVs localmente si quieres
    restart: "no"              # es un job, no un server