version: "3.8"

services:
  usuarios:
    build: ./usuarios
    container_name: etl_usuarios
    environment:
      MS1_URL: "http://54.234.118.130:8000"
    volumes:
      - ./output:/app/output  
    restart: "no"      
  peliculas:
    build: ./Peliculas
    container_name: etl_peliculas
    environment:
      MS2_URL: http://54.234.118.130:3000"
    volumes:
      - ./output:/app/output
    restart: "no"      