services:
  usuarios:
    build: ./usuarios
    container_name: etl_usuarios
    env_file:
      - .env
    environment:
      MS1_URL: ${MS1_URL}
    volumes:
      - ./output:/app/output
    restart: "no"
  peliculas:
    build: ./Peliculas
    container_name: etl_peliculas
    env_file:
      - .env
    environment:
      MS2_URL: ${MS2_URL}
    volumes:
      - ./output:/app/output
    restart: "no"
  foro:
    build: ./Foro
    container_name: etl_foro
    env_file:
      - .env
    environment:
      MS3_URL: ${MS3_URL}
    volumes:
      - ./output:/app/output
    restart: "no"
